sonar.projectKey=wsciaroni_wrtos
sonar.organization=wsciaroni

# Name and version displayed in the SonarCloud UI
sonar.projectName=wrtos
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=wrtos-core\src,wrtos-codegen\src,wrtos-wcet\src
sonar.sourceEncoding=UTF-8

# Import LCOV code coverage reports
sonar.rust.lcov.reportPaths=lcov.info
