use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SystemConfig {
    pub tick_rate_hz: u32,
    pub major_cycle_frames: usize,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TaskConfig {
    pub name: String,
    pub func: String,
    pub frames: Vec<usize>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ScheduleConfig {
    pub system: SystemConfig,
    pub tasks: Vec<TaskConfig>,
}

#[derive(Debug, PartialEq, Eq)]
pub enum ValidationError {
    InvalidTickRate,
    InvalidMajorCycleFrames,
    EmptyTaskFrames(String),
    FrameIndexOutOfRange { task: String, frame: usize, limit: usize },
    EmptyTaskFunction(String),
    InvalidTaskFunctionCharacters(String),
}

impl std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ValidationError::InvalidTickRate => write!(f, "Tick rate must be greater than zero"),
            ValidationError::InvalidMajorCycleFrames => write!(f, "Major cycle frames must be greater than zero"),
            ValidationError::EmptyTaskFrames(task) => write!(f, "Task '{}' must be scheduled in at least one frame", task),
            ValidationError::FrameIndexOutOfRange { task, frame, limit } => {
                write!(f, "Task '{}' scheduled in frame {} which exceeds major cycle limit of {}", task, frame, limit)
            }
            ValidationError::EmptyTaskFunction(task) => write!(f, "Task '{}' has an empty function path", task),
            ValidationError::InvalidTaskFunctionCharacters(task) => write!(f, "Task '{}' has invalid characters in its function path (only alphanumeric, underscores, and colons are allowed to prevent code injection)", task),
        }
    }
}

pub fn parse_config(toml_str: &str) -> Result<ScheduleConfig, toml::de::Error> {
    toml::from_str(toml_str)
}

pub fn validate_config(config: &ScheduleConfig) -> Result<(), ValidationError> {
    if config.system.tick_rate_hz == 0 {
        return Err(ValidationError::InvalidTickRate);
    }
    if config.system.major_cycle_frames == 0 {
        return Err(ValidationError::InvalidMajorCycleFrames);
    }

    for task in &config.tasks {
        if task.func.trim().is_empty() {
            return Err(ValidationError::EmptyTaskFunction(task.name.clone()));
        }

        // Security check: Prevent code injection in codegen by restricting allowed characters
        if !task.func.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':') {
            return Err(ValidationError::InvalidTaskFunctionCharacters(task.name.clone()));
        }

        if task.frames.is_empty() {
            return Err(ValidationError::EmptyTaskFrames(task.name.clone()));
        }
        for &frame in &task.frames {
            if frame >= config.system.major_cycle_frames {
                return Err(ValidationError::FrameIndexOutOfRange {
                    task: task.name.clone(),
                    frame,
                    limit: config.system.major_cycle_frames,
                });
            }
        }
    }

    Ok(())
}

pub fn generate_schedule_code(config: &ScheduleConfig) -> String {
    let tick_rate_hz = config.system.tick_rate_hz;
    let major_cycle_frames = config.system.major_cycle_frames;

    let mut schedule_rows = String::new();
    for i in 0..major_cycle_frames {
        let mut row_tasks = Vec::new();
        for task in &config.tasks {
            if task.frames.contains(&i) {
                row_tasks.push(task.func.clone());
            }
        }
        if row_tasks.is_empty() {
            schedule_rows.push_str("    &[],\n");
        } else {
            schedule_rows.push_str("    &[\n");
            for task_func in row_tasks {
                schedule_rows.push_str(&format!("        {},\n", task_func));
            }
            schedule_rows.push_str("    ],\n");
        }
    }

    format!(
        r#"// Automatically generated by wrtos-codegen. Do not edit.

pub const TICK_RATE_HZ: u32 = {};
pub const MAJOR_CYCLE_FRAMES: usize = {};

pub const SCHEDULE: &[&[fn()]] = &[
{}];
"#,
        tick_rate_hz, major_cycle_frames, schedule_rows
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const VALID_TOML: &str = r#"
        [system]
        tick_rate_hz = 1000
        major_cycle_frames = 4

        [[tasks]]
        name = "t1"
        func = "path::to::t1"
        frames = [0, 2]

        [[tasks]]
        name = "t2"
        func = "path::to::t2"
        frames = [1, 3]
    "#;

    #[test]
    fn test_parse_valid_config() {
        let res = parse_config(VALID_TOML);
        assert!(res.is_ok());
        let config = res.unwrap();
        assert_eq!(config.system.tick_rate_hz, 1000);
        assert_eq!(config.system.major_cycle_frames, 4);
        assert_eq!(config.tasks.len(), 2);
        assert_eq!(config.tasks[0].name, "t1");
        assert_eq!(config.tasks[0].func, "path::to::t1");
        assert_eq!(config.tasks[0].frames, vec![0, 2]);
    }

    #[test]
    fn test_parse_invalid_toml() {
        let invalid_toml = "invalid toml content";
        let res = parse_config(invalid_toml);
        assert!(res.is_err());
    }

    #[test]
    fn test_validate_valid_config() {
        let config = parse_config(VALID_TOML).unwrap();
        let res = validate_config(&config);
        assert_eq!(res, Ok(()));
    }

    #[test]
    fn test_validate_invalid_tick_rate() {
        let mut config = parse_config(VALID_TOML).unwrap();
        config.system.tick_rate_hz = 0;
        let res = validate_config(&config);
        assert_eq!(res, Err(ValidationError::InvalidTickRate));
    }

    #[test]
    fn test_validate_invalid_major_cycle_frames() {
        let mut config = parse_config(VALID_TOML).unwrap();
        config.system.major_cycle_frames = 0;
        let res = validate_config(&config);
        assert_eq!(res, Err(ValidationError::InvalidMajorCycleFrames));
    }

    #[test]
    fn test_validate_empty_task_frames() {
        let mut config = parse_config(VALID_TOML).unwrap();
        config.tasks[0].frames = vec![];
        let res = validate_config(&config);
        assert_eq!(res, Err(ValidationError::EmptyTaskFrames("t1".to_string())));
    }

    #[test]
    fn test_validate_frame_index_out_of_range() {
        let mut config = parse_config(VALID_TOML).unwrap();
        config.tasks[0].frames = vec![0, 4]; // major cycle is 4, so max allowed is 3
        let res = validate_config(&config);
        assert_eq!(
            res,
            Err(ValidationError::FrameIndexOutOfRange {
                task: "t1".to_string(),
                frame: 4,
                limit: 4
            })
        );
    }

    #[test]
    fn test_validate_empty_task_function() {
        let mut config = parse_config(VALID_TOML).unwrap();
        config.tasks[0].func = "".to_string();
        let res = validate_config(&config);
        assert_eq!(res, Err(ValidationError::EmptyTaskFunction("t1".to_string())));
    }

    #[test]
    fn test_validate_invalid_task_function_chars() {
        let mut config = parse_config(VALID_TOML).unwrap();
        // Inject payload: dummy_func], &[], // bypass
        config.tasks[0].func = "dummy_func], &[], // bypass".to_string();
        let res = validate_config(&config);
        assert_eq!(res, Err(ValidationError::InvalidTaskFunctionCharacters("t1".to_string())));
    }

    #[test]
    fn test_generate_schedule_code() {
        let config = parse_config(VALID_TOML).unwrap();
        let code = generate_schedule_code(&config);
        // Verify code contains structural expectations
        assert!(code.contains("pub const TICK_RATE_HZ: u32 = 1000;"));
        assert!(code.contains("pub const MAJOR_CYCLE_FRAMES: usize = 4;"));
        assert!(code.contains("pub const SCHEDULE: &[&[fn()]] = &["));
        assert!(code.contains("path::to::t1"));
        assert!(code.contains("path::to::t2"));
    }

    #[test]
    fn test_generate_schedule_code_with_empty_frames() {
        let toml_content = r#"
            [system]
            tick_rate_hz = 1000
            major_cycle_frames = 3

            [[tasks]]
            name = "t1"
            func = "t1_func"
            frames = [0]
        "#;
        let config = parse_config(toml_content).unwrap();
        let code = generate_schedule_code(&config);
        assert!(code.contains("pub const TICK_RATE_HZ: u32 = 1000;"));
        assert!(code.contains("pub const MAJOR_CYCLE_FRAMES: usize = 3;"));
        assert!(code.contains("    &[\n        t1_func,\n    ],"));
        assert!(code.contains("    &[],")); // Frame 1 is empty
        assert!(code.contains("    &[],")); // Frame 2 is empty
    }

    #[test]
    fn test_validation_error_display() {
        assert_eq!(
            ValidationError::InvalidTickRate.to_string(),
            "Tick rate must be greater than zero"
        );
        assert_eq!(
            ValidationError::InvalidMajorCycleFrames.to_string(),
            "Major cycle frames must be greater than zero"
        );
        assert_eq!(
            ValidationError::EmptyTaskFrames("t1".to_string()).to_string(),
            "Task 't1' must be scheduled in at least one frame"
        );
        assert_eq!(
            ValidationError::FrameIndexOutOfRange {
                task: "t1".to_string(),
                frame: 4,
                limit: 4
            }.to_string(),
            "Task 't1' scheduled in frame 4 which exceeds major cycle limit of 4"
        );
        assert_eq!(
            ValidationError::EmptyTaskFunction("t1".to_string()).to_string(),
            "Task 't1' has an empty function path"
        );
    }
}
